### ISSUE TITLE
Compatibility For Guarding

### ISSUE THREAD

**Issue by Fyoncle** [masik16u/More-Armor-Trims-Fabric#14]
Guarding mod is adding Netherite Shield which is trimmable, but when More Armor Trims mod trims used, it is completely black.

I use 1.20.1 Fabric.

**Comment by masik16u** [comment]
The textures used in the mod Guarding are created by the Guarding's author, so I suspect that it doesn't support any custom armor trims

**Comment by Fyoncle** [comment]
> The textures used in the mod Guarding are created by the Guarding's author, so I suspect that it doesn't support any custom armor trims

You mind adding compat yourself?

**Comment by masik16u** [comment]
I tried but it doesn't work, maybe it's hard-coded

**Comment by Fyoncle** [comment]
> I tried but it doesn't work, maybe it's hard-coded

Other people opened issue about compat but he REFUSED and tell them to ask the other mod devs to add compat for Guarding so i thought of asking to you.

**Comment by masik16u** [comment]
I found a way to do it, so I will close this issue

**Comment by Fyoncle** [comment]
> I found a way to do it, so I will close this issue

❤️

**Comment by Fyoncle** [comment]
Did you manage to get it working?  I use 1.20.1

**Comment by masik16u** [comment]
> Did you manage to get it working? I use 1.20.1

Yes, I just haven't had a chance to draw everything

**Comment by Fyoncle** [comment]
> > Did you manage to get it working? I use 1.20.1
> 
> Yes, I just haven't had a chance to draw everything

Thank you for fixing that! :D ❤️
